project:
  type: website

website:
  title: "Gareth Edwards"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Articles
      - href: cv.pdf
        text: CV

format:
  html:
    theme: cosmo # Or whatever theme you are currently using