project:
  type: website
  render:
    - "*.qmd"               # This grabs your index.qmd and about.qmd
    - "**/viz build.ipynb"  # This ONLY grabs notebooks named exactly this in any subfolder

website:
  title: "Football Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Gareth1995

format:
  html:
    theme: cosmo # You can change this to darkly, sketchy, litera, etc.
    css: styles.css